### ISSUE TITLE
trello refresh: API endpoint is not found

### ISSUE THREAD

**Issue by work67** [mheap/trello-cli#74]
When you run:
trello refresh

you get:
(node:17350) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
/home/user/programs/trello-cli/src/translator.js:211
                  throw err;
Error: The requested resource was not found.
.....
  statusCode: 404,
  responseBody: 'The requested resource was not found.',
  statusMessage: 'Not Found'
}
...

Can anyone reproduce?

My guess is Trello/Atlassian have changed the API urls ?

They've recently done a major Trello upgrade/changes/launches of new features. That might have caused it.

**Comment by mheap** [comment]
Hey @work67! I've just tested and this seems to be working for me. I've just released `v0.4.0` with a fix for the circular dependency issue. Could you update and try again?

**Comment by work67** [comment]
Hi, @mheap !

I've updated to 0.4.0.
I've ran npm install to refresh node modules.

Tried trello refresh - same messages:
...
  statusCode: 404,
  responseBody: 'The requested resource was not found.',
  statusMessage: 'Not Found'
}
---

Then I noticed that the npm lock file package-lock.json is always changed after npm install.
I thought that might be the problem.
Deleted package-lock.json and also node_modules.
Ran npm install.

New test of trello refresh - same thing:

---
/opt/trello-cli/src/translator.js:211
                  throw err;
                  ^

Error: The requested resource was not found.
    at Request._callback (/opt/trello-cli/node_modules/node-trello/lib/node-trello.js:88:13)
    at Request.self.callback (/opt/trello-cli/node_modules/request/request.js:187:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/opt/trello-cli/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/opt/trello-cli/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  statusCode: 404,
  responseBody: 'The requested resource was not found.',
  statusMessage: 'Not Found'
}
---

It's probably working fine, as it is taking 20-30 seconds for the refresh to run.

Probably some small not important part of the refresh is having trouble.

I can see the problem is related to "node-trello".

It's either that package that is outdated somehow OR maybe my trello account type is different from yours ? For example - works on trello gold/premium, and is not ok on trello free ?

**Comment by mheap** [comment]
I've just released version `0.4.2` with additional logging

Could you run `TRELLO_LOG=debug trello refresh` and share the output? It should look similar to the following:

```
debug: Syncing lists (boards :: 603cc6e791019c2840ea5f2e :: TestNoList)
```

Once it shows which board is causing the issue can you investigate the board? It may not have any lists, or the list may have titles with unusual characters etc. You're looking for anything unusual

**Comment by work67** [comment]
Tried that and it hung on a board having name like:
"ABC/Word (#WordWord))"
Tested what happens if I rename the board to "ABC Word Word" - same thing - did not fix it.

The lists in that board are all normal - no fancy chars.
There are other boards with #, () and '/' in their names - they work ok.

So maybe its my node version - v14.15.4 ?
What's yours?
I can switch my node version and test.

**Comment by mheap** [comment]
I'm running node `v15.10.0`

In the debug output did it output an ID in addition to a name?

**Comment by work67** [comment]
yep, all boards and lists have ID-s all fine with the ID-s.
Tried with node 15.10.0 - same thing. Will debug some more - let's see if I find sth.

**Comment by mheap** [comment]
Is the board something that's private or something that you could invite me to? I could try and replicate locally

**Comment by work67** [comment]
Found the problem:
during the sync made at translator.js around line 203, if we have deleted board(s) in the cacheFile (translation.json), the code tries to download those deleted boards and the request fails with 404/not found.
To replicate, create a test board, then close it, then delete if and run the sync.

do debug some more I've added:
              var that = this;
right before:
getThrottled("/1/boards/" + board + "/lists", function(
and added :
                  that.logger.debug(boardInfo.name, cachePath, data);
right before 
                  throw err;

This way I saw which board was causing the 404.

**Comment by work67** [comment]
The issue is more of a cosmetic one, I suppose nothing important related to the refresh/sync fails actually.
It's just the message that is ugly.

**Comment by mheap** [comment]
Excellent debugging work! I've just released `v0.4.3` with a fix for this

**Comment by work67** [comment]
Tested. It's fixed indeed!
Thanks! Awesome!
